language: groovy
jdk:
  - openjdk6
before_install:
  - sudo add-apt-repository -y ppa:groovy-dev/grails
  - sudo apt-get update
  - sudo apt-get install grails-1.3.7
  - wget http://mirrors.ibiblio.org/pub/mirrors/maven2/ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3.jar
  - mkdir -p ~/.ant/lib
  - cp ant-contrib-1.0b3.jar ~/.ant/lib
install: /bin/true
before_script:
  - ant init-build
script: ant bundle